### ISSUE TITLE
Bots is off

### ISSUE THREAD

**Issue by PGeneveePerso** [cyrilcaillat/ma-liste-courses#3]
**Describe the bug**
Bot "Ma liste de courses" is not responding in the discussions since 1 week.

**To Reproduce**
Bot included in a discussion not responding when prompting add, list or delall

**Expected behavior**
Nothing happens

**Desktop (please complete the following information):**
 - telegram iOs and Android

**Comment by cyrilcaillat** [comment]
The problem is fixed.

**Comment by PGeneveePerso** [comment]
Perfect, thank you

**Comment by PGeneveePerso** [comment]
Perfect, thank you
